services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000 # Find with the "id" command
      - PGID=1000 # Find with the "id" command
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /run/media/cp/4THDD01/Media/Shows:/data/shows
      - /run/media/cp/4THDD01/Media/Shows-kids:/data/shows-kids
      - /run/media/cp/4THDD01/Media/Movies:/data/movies
      - /run/media/cp/4THDD01/Media/Movies-kids:/data/movies-kids
      - /run/media/cp/4THDD01/Media/Movies-home:/data/movies-home
      - /run/media/cp/4THDD01/Media/Music:/data/music
    ports:
      - 8096:8096
#    restart: 'unless-stopped'
# Returns error /dev/dri/card0 not found. card1 and card2 are there
#    devices:
#      - /dev/dri/renderD128:/dev/dri/renderD128
#      - /dev/dri/card0:/dev/dri/card0
