services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000 # Find with the "id" command
      - PGID=1000 # Find with the "id" command
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /run/media/cp/4THDD01/Videos/Shows:/data/tvshows
      - /run/media/cp/4THDD01/Videos/Movies:/data/movies
    ports:
      - 8096:8096
    restart: 'unless-stopped'
# Returns error /dev/dri/card0 not found. card1 and card2 are there
#    devices:
#      - /dev/dri/renderD128:/dev/dri/renderD128
#      - /dev/dri/card0:/dev/dri/card0
