services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000 # Find with the "id" command
      - PGID=1000 # Find with the "id" command
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://${URL} #optional
    volumes:
      - ./config:/config
      - ${MEDIA_DIR}/Movies:/data/movies
      - ${MEDIA_DIR}/Movies-kids:/data/movies-kids
      - ${MEDIA_DIR}/Movies-home:/data/movies-home
      - ${MEDIA_DIR}/Shows:/data/shows
      - ${MEDIA_DIR}/Shows-kids:/data/shows-kids
      - ${MEDIA_DIR}/Music:/data/music
      - ${MEDIA_DIR}/Documentaries:/data/Documentaries
    env_file:
      - .env
    devices:
      - /dev/dri:/dev/dri
    ports:
      - '8096:8096'
    restart: no
